language: python
python:
   - "3.4"
   
# command to install dependencies
install: "pip install -r requirements.txt"

before_install:
    - pip install pytest-cov
    # - pip install coveralls

script: 
    # - "python test.py"
    - nosetests --with-coverage --cover-package=test

after_sucess:
    - coveralls